//
// Autogenerated by Thrift Compiler (0.7.0-en-11139b3b5cb61e817408c6e84b0e1c258bf6c6ae)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


  // Define types and services

  var Thrift = require('evernote-thrift').Thrift;

  module.exports.AuthenticationErrorCode = {
    'UNKNOWN' : 1,
    'BAD_OPENID_FORMAT' : 2,
    'INTERNAL_ERROR' : 3,
    'DATA_REQUIRED' : 4,
    'OPENID_EXPIRED' : 5,
    'UNSUPPORTED_OPERATION' : 6,
    'INVALID_ARGUMENT' : 7,
    'INVALID_AUTH' : 8,
    'OPENID_ALREADY_TAKEN' : 9,
    'USER_NOT_REGISTERED' : 10,
    'USER_NOT_ASSOCIATED' : 11,
    'USER_ALREADY_ASSOCIATED' : 12,
    'EMAIL_ASSOCIATED_DIFFERENT_UID' : 13
  };

  module.exports.UserNotFoundException = Thrift.Exception.define('UserNotFoundException',  {
    1: { alias: 'errorCode', type: Thrift.Type.I32 },
    2: { alias: 'message', type: Thrift.Type.STRING }
  });

  module.exports.SystemException = Thrift.Exception.define('SystemException',  {
    1: { alias: 'errorCode', type: Thrift.Type.I32 },
    2: { alias: 'message', type: Thrift.Type.STRING }
  });

  module.exports.BadOpenIDException = Thrift.Exception.define('BadOpenIDException',  {
    1: { alias: 'errorCode', type: Thrift.Type.I32 },
    2: { alias: 'message', type: Thrift.Type.STRING }
  });

  module.exports.UserException = Thrift.Exception.define('UserException',  {
    1: { alias: 'errorCode', type: Thrift.Type.I32 },
    2: { alias: 'message', type: Thrift.Type.STRING }
  });

