//
// Autogenerated by Thrift Compiler (0.7.0-en-11139b3b5cb61e817408c6e84b0e1c258bf6c6ae)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


  // Define types and services

  var Thrift = require('evernote-thrift').Thrift;

  module.exports.EDAMMarketErrorCode = {
    'UNKNOWN' : 1,
    'INVALID_CART_CONTENT' : 10,
    'INSUFFICIENT_STOCK' : 11,
    'ORDER_TOO_LARGE' : 12,
    'UNSUPPORTED_SHIPPING_COUNTRY' : 13,
    'INVALID_ADDRESS' : 14,
    'INVALID_PAYMENT_METHOD' : 15,
    'UNAVAILABLE_SHIPPING_METHOD' : 16,
    'INVALID_CHECKOUT_COMMENT' : 17,
    'EXPIRED_CART' : 18,
    'UNKNOWN_PRODUCT' : 19,
    'INVALID_PRODUCT_FOR_MARKET' : 20,
    'INVALID_CATALOG_DEFINITION' : 21,
    'MISMATCHED_CART_VERSION' : 22,
    'INVALID_CART_ITEM_QUANTITY' : 23,
    'INVALID_SHIPPING_METHOD' : 24,
    'EMPTY_CART' : 25,
    'INVALID_CART_SEGMENT' : 26,
    'INVALID_BUSINESS_TIN' : 27,
    'INVALID_TAX_INFORMATION' : 28,
    'PAYMENT_UNKNOWN_ERROR' : 30,
    'PAYMENT_USER_ERROR' : 31,
    'PAYMENT_FRAUD_ERROR' : 32,
    'PAYMENT_GATEWAY_ERROR' : 33,
    'PAYMENT_ACQUIRER_ERROR' : 34,
    'PAYMENT_ISSUING_BANK_ERROR' : 35,
    'PAYMENT_DUPLICATE_ERROR' : 36,
    'FULFILLMENT_UNKNOWN_ERROR' : 50
  };

  module.exports.EDAMMarketException = Thrift.Exception.define('EDAMMarketException',  {
    1: { alias: 'errorCode', type: Thrift.Type.I32 },
    2: { alias: 'message', type: Thrift.Type.STRING },
    3: { alias: 'parameter', type: Thrift.Type.STRING },
    4: { alias: 'removedCartItems', type: Thrift.Type.MAP, def: Thrift.Map.define(Thrift.Type.STRING, Thrift.Type.I32 )  }
  });

